baseurl = "https://birthed-by-the-necrophage.github.io/"
languageCode = "en-us"
paginate = 5
theme = "hugo-theme-bootstrap4-blog"
title = "Birthed by the Necrophage"
[[menu.sidebar]]
[[menu.sidebar]]
name = "Oscilabot"
url = "http://oscilabot.com"
[params]
author = ""
date_format = "Mon Jan 02, 2006"
description = "A D&D Campaign Log"
[params.sidebar]
about = "This website logs the events of a tabletop D&D campaign."
[params.social]
twitter = "username"
[permalinks]
page = "/:slug/"
post = "/:year/:month/:title/"
